function run_spectral_filter_job_list(JOBLIST)
% run_spectral_filter_job_list(JOBLIST)
% This function batch-executes a list of image spectral filtering jobs.
%
% INPUTS
%   JOBLIST = Structure containing the sub-structures that each
%             specify the processing parameters of the individual batch
%             jobs. The JOBLIST structure is generated by executing 
%             the function spectral_filter_job_list.m, e.g., 
%             JobList = spectral_filter_job_list;
%
% OUTPUTS
%   None
%
% See Also
%   run_spectral_filter_job_file, spectral_filter_job_list

% Begin function %

% Count the number of jobs in the job list
number_of_jobs = length(JOBLIST);

% Run each job in the job list.
for k = 1 : number_of_jobs
   run_spectral_filter_job_file(JOBLIST(k)); 
end

end